/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemanegocio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author feded
 */
public class EditarP extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarP
     */
    Connection conc;
    public EditarP() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLEditarP = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLecodigo = new javax.swing.JLabel();
        jLemarca = new javax.swing.JLabel();
        jLedetalle = new javax.swing.JLabel();
        jLeprecio = new javax.swing.JLabel();
        jTFecodigo = new javax.swing.JTextField();
        jTFemarca = new javax.swing.JTextField();
        jTFedetalle = new javax.swing.JTextField();
        jTFeprecio = new javax.swing.JTextField();
        jBebuscar = new javax.swing.JButton();
        jBeguardar = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLEditarP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLEditarP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEditarP.setText("Editar Productos");
        jLEditarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLecodigo.setText("CODIGO");

        jLemarca.setText("MARCA");

        jLedetalle.setText("DETALLE");

        jLeprecio.setText("PRECIO");

        jTFeprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFeprecioActionPerformed(evt);
            }
        });

        jBebuscar.setText("BUSCAR");
        jBebuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBebuscarActionPerformed(evt);
            }
        });

        jBeguardar.setText("GUARDAR");
        jBeguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLEditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLemarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLecodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLedetalle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLeprecio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFecodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBebuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFemarca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFedetalle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFeprecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBeguardar)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLEditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLecodigo)
                    .addComponent(jTFecodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBebuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLemarca)
                    .addComponent(jTFemarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLedetalle)
                    .addComponent(jTFedetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLeprecio)
                    .addComponent(jTFeprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBeguardar)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFeprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFeprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFeprecioActionPerformed

    private void jBeguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeguardarActionPerformed
        try {
                conc = DriverManager.getConnection("jdbc:mysql://localhost/sistemanegocio","root","");
                Statement stmt = conc.createStatement();
                               
                String ed = "UPDATE listado SET  marca=?, detalle=?, precio=?  WHERE codigo =?";
                
                PreparedStatement pt = conc.prepareStatement(ed);
                pt.setString(1, jTFemarca.getText());
                pt.setString(2, jTFedetalle.getText());
                pt.setString(3, jTFeprecio.getText());
                pt.setString(4, jTFecodigo.getText());
                pt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto actualizado");
                conc.close();
            } catch (SQLException ex) {
                Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
               
            }
    }//GEN-LAST:event_jBeguardarActionPerformed

    private void jBebuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBebuscarActionPerformed
        try {
            Connection conc = DriverManager.getConnection("jdbc:mysql://localhost/sistemanegocio","root","");
            Statement stl = conc.createStatement();
            ResultSet lp = stl.executeQuery("SELECT * FROM listado WHERE codigo="+jTFecodigo.getText());
            
                
                           
                while (lp.next()) {
                String addcod = lp.getString("codigo");
                jTFecodigo.setText(addcod);
                String addmar = lp.getString("marca");
                jTFemarca.setText(addmar);
                String adddet = lp.getString("detalle");
                jTFedetalle.setText(adddet);
                String addprec = lp.getString("precio");
                jTFeprecio.setText(addprec);
                
            }

        } catch (SQLException ex) {
            Logger.getLogger(ListaPrecios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBebuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBebuscar;
    private javax.swing.JButton jBeguardar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLEditarP;
    private javax.swing.JLabel jLecodigo;
    private javax.swing.JLabel jLedetalle;
    private javax.swing.JLabel jLemarca;
    private javax.swing.JLabel jLeprecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFecodigo;
    private javax.swing.JTextField jTFedetalle;
    private javax.swing.JTextField jTFemarca;
    private javax.swing.JTextField jTFeprecio;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
