/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemanegocio;




import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author feded
 */
public class NuevoP extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoP
     * @throws java.sql.SQLException
     */
    
    
        Connection con;
    
    public NuevoP() throws SQLException {
        initComponents();
                
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNuevo = new javax.swing.JLabel();
        jLncodigo = new javax.swing.JLabel();
        jLnmarca = new javax.swing.JLabel();
        jLndetale = new javax.swing.JLabel();
        jLnprecio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFncodigo = new javax.swing.JTextField();
        jTFnmarca = new javax.swing.JTextField();
        jTFndetalle = new javax.swing.JTextField();
        jTFnprecio = new javax.swing.JTextField();
        jBnguardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNuevo.setText("Nuevo Producto");
        jLNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLncodigo.setText("CODIGO");

        jLnmarca.setText("MARCA");

        jLndetale.setText("DETALLE");

        jLnprecio.setText("PRECIO");

        jTFncodigo.setEnabled(false);

        jBnguardar.setText("GUARDAR");
        jBnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLndetale)
                            .addComponent(jLncodigo)
                            .addComponent(jLnmarca)
                            .addComponent(jLnprecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFncodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jTFnmarca)
                            .addComponent(jTFndetalle)
                            .addComponent(jTFnprecio)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jBnguardar)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLncodigo)
                    .addComponent(jTFncodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnmarca)
                    .addComponent(jTFnmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLndetale)
                    .addComponent(jTFndetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnprecio)
                    .addComponent(jTFnprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBnguardar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnguardarActionPerformed
            
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/sistemanegocio","root","");
                Statement stmt = con.createStatement();
                stmt.executeUpdate("INSERT INTO listado (marca, detalle, precio) VALUES('"+jTFnmarca.getText()+"','"+jTFndetalle.getText()+"','"+jTFnprecio.getText()+"')");
                JOptionPane.showMessageDialog(null, "Producto registrado");
                
                jTFncodigo.setText(null);
                jTFnmarca.setText(null);
                jTFndetalle.setText(null);
                jTFnprecio.setText(null);
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
               
            }
            //(marca, detalle, precio)
           // jTFncodigo.setText(null);
                //jTFnmarca.setText(null);
                // jTFndetalle.setText(null);
                //jTFnprecio.setText(null);
    }//GEN-LAST:event_jBnguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnguardar;
    private javax.swing.JLabel jLNuevo;
    private javax.swing.JLabel jLncodigo;
    private javax.swing.JLabel jLndetale;
    private javax.swing.JLabel jLnmarca;
    private javax.swing.JLabel jLnprecio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFncodigo;
    private javax.swing.JTextField jTFndetalle;
    private javax.swing.JTextField jTFnmarca;
    private javax.swing.JTextField jTFnprecio;
    // End of variables declaration//GEN-END:variables
}
