/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemanegocio;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author feded
 */
public class Ventas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    Connection conc;
    int vcant2, vcant;
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLventa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLvcodigo = new javax.swing.JLabel();
        jLvmarca = new javax.swing.JLabel();
        jLvdetalle = new javax.swing.JLabel();
        jLvprecio = new javax.swing.JLabel();
        jLvcantidad = new javax.swing.JLabel();
        jTFvcodigo = new javax.swing.JTextField();
        jTFvmarca = new javax.swing.JTextField();
        jTFvdetalle = new javax.swing.JTextField();
        jTFvprecio = new javax.swing.JTextField();
        jBvguardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSvcantidad = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLventa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLventa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLventa.setText("Ventas");
        jLventa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLvcodigo.setText("CODIGO");

        jLvmarca.setText("MARCA");

        jLvdetalle.setText("DETALLE");

        jLvprecio.setText("PRECIO");

        jLvcantidad.setText("CANTIDAD");

        jTFvmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvmarcaActionPerformed(evt);
            }
        });

        jBvguardar.setText("GUARDAR");
        jBvguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvguardarActionPerformed(evt);
            }
        });

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSvcantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLvmarca)
                            .addComponent(jLvcodigo)
                            .addComponent(jLvdetalle)
                            .addComponent(jLvprecio)
                            .addComponent(jLvcantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFvmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(jTFvdetalle)
                                .addComponent(jTFvprecio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFvcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSvcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jBvguardar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLventa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLventa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvcodigo)
                    .addComponent(jTFvcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvmarca)
                    .addComponent(jTFvmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvdetalle)
                    .addComponent(jTFvdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvprecio)
                    .addComponent(jTFvprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvcantidad)
                    .addComponent(jSvcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBvguardar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFvmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFvmarcaActionPerformed

    private void jBvguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvguardarActionPerformed
        try {
                conc = DriverManager.getConnection("jdbc:mysql://localhost/sistemanegocio","root","");
                Statement stmt = conc.createStatement();
                ResultSet stock2 = stmt.executeQuery("SELECT (cantidad) FROM listado WHERE codigo="+jTFvcodigo.getText());
                    stock2.first();
                    vcant = (int) stock2.getInt(1);
                    String  b = jTFvcodigo.getText();
                    vcant2 = (int)jSvcantidad.getValue();
                    vcant = vcant - vcant2;
                
                String table = "UPDATE listado SET cantidad =?  WHERE codigo =?";
                PreparedStatement pt = conc.prepareStatement(table);
                pt.setInt(1, vcant);
                pt.setString(2, b);
                pt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Producto registrado");
                conc.close();
            } catch (SQLException ex) {
                Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
               
            }
    }//GEN-LAST:event_jBvguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection conc = DriverManager.getConnection("jdbc:mysql://localhost/sistemanegocio","root","");
            Statement stl = conc.createStatement();
            ResultSet lp = stl.executeQuery("SELECT * FROM listado WHERE codigo="+jTFvcodigo.getText());
            
                while (lp.next()) {
                String addcod = lp.getString("codigo");
                jTFvcodigo.setText(addcod);
                String addmar = lp.getString("marca");
                jTFvmarca.setText(addmar);
                String adddet = lp.getString("detalle");
                jTFvdetalle.setText(adddet);
                String addprec = lp.getString("precio");
                jTFvprecio.setText(adddet);
                
            }

        } catch (SQLException ex) {
            Logger.getLogger(ListaPrecios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jBvguardar;
    private javax.swing.JLabel jLvcantidad;
    private javax.swing.JLabel jLvcodigo;
    private javax.swing.JLabel jLvdetalle;
    private javax.swing.JLabel jLventa;
    private javax.swing.JLabel jLvmarca;
    private javax.swing.JLabel jLvprecio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSvcantidad;
    private javax.swing.JTextField jTFvcodigo;
    private javax.swing.JTextField jTFvdetalle;
    private javax.swing.JTextField jTFvmarca;
    private javax.swing.JTextField jTFvprecio;
    // End of variables declaration//GEN-END:variables
}
